PrismAdminAPI/Models/ChapterContent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Models
{
    public class ChapterContent
    {
        public long ChapterContentId { get; set; }

        [DisplayName("Standard")]
        public long StandardId { get; set; }

        [DisplayName("Medium")]
        public long MediumId { get; set; }

        [DisplayName("Subject")]
        public long SubjectId { get; set; }

        [DisplayName("Chapter")]
        public long ChapterId { get; set; }

        [DisplayName("Section")]
        public long SectionId { get; set; }

        [AllowHtml]
        [DisplayName("Content")]
        public string ChapterTextContents { get; set; }

        public List<string> ChapterImageContentsPath { get; set; }

        [DisplayName("Upload Image")]
        public HttpPostedFileBase[] ChapterImageContents { get; set; }

        public string ChapterVideoContentsPath { get; set; }

        [DisplayName("Upload Video")]
        public HttpPostedFileBase ChapterVideoContents { get; set; }

        public string ContentTypeString { get; set; }

        [Display(Name = "Content Type")]
        public ChapterContentType ContentType { get; set; }

        public bool IsActive { get; set; }

        [Display(Name = "Disable Section")]
        public bool? IsSectionDisabled { get; set; }

        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }

        public IEnumerable<SelectListItem> StandardList { get; set; }
    }

    public enum ChapterContentType
    {
        Text = 1,
        Image = 2,
        Video = 3   
    }

    public class ChapterContentViewModel
    {
        public long ChapterContentId { get; set; }
        public long SectionId { get; set; }
        public string SectionName { get; set; }
        public string ContentType { get; set; }
        public long ChapterId { get; set; }
        public string ChapterName { get; set; }
        public long SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string ChapterImageContents { get; set; }
        public string ChapterVideoContents { get; set; }
        [AllowHtml]
        public string ChapterTextContents { get; set; }
        public bool IsSectionDisabled { get; set; }
        public long StandardId { get; set; }
        public string StandardName { get; set; }
        public long MediumId { get; set; }
        public string MediumName { get; set; }
    }


}

PrismAdminAPI/Controllers/ChapterContentController.cs
using PrismAdminAPI.BAL;
using PrismAdminAPI.Manager;
using PrismAdminAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Controllers
{
    public class ChapterContentController : Controller
    {
        private readonly IChapterManager chapterManager;
        private readonly IStandardManager standardManager;
        private readonly IConfigurationManager configurationManager;
        private readonly ISectionManager sectionManager;
        private readonly IChapterContentManager chapterContentManager;
        public ChapterContentController(IChapterManager _chapterManager,
            IStandardManager _standardManager,
            IConfigurationManager _configurationManager,
            ISectionManager _sectionManager,
            IChapterContentManager _chapterContentManager)
        {
            chapterManager = _chapterManager;
            standardManager = _standardManager;
            configurationManager = _configurationManager;
            sectionManager = _sectionManager;
            chapterContentManager = _chapterContentManager;
        }

        [Route("getchaptercontent")]
        [Route("ChapterContent/ListChapterContent")]
        public ActionResult ListChapterContent()
        {
            ChapterContent chapterContent = new ChapterContent();
            chapterContent = GetChapterContentObjectDetails(chapterContent);
            return View(chapterContent);
        }

       

        [HttpPost]
        public ActionResult GetChapterContent(ChapterContent _chapterContent)
        {
            var _chapterContentList = chapterContentManager.GetChapterContent(_chapterContent.StandardId,
                _chapterContent.MediumId, _chapterContent.ChapterId, _chapterContent.SectionId, _chapterContent.SubjectId);
            return PartialView("_ListChapterContent", _chapterContentList);
        }

        [HttpGet]
        public ActionResult GetChapterContentOnSection(ChapterContent _chapterContent)
        {
            var _chapterContentList = chapterContentManager.GetChapterContent(_chapterContent.StandardId,
                _chapterContent.MediumId, _chapterContent.ChapterId, _chapterContent.SectionId, _chapterContent.SubjectId, false);
            return Json(_chapterContentList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetChapterContentOnSectionPrint(ChapterContent _chapterContent)
        {
            var _chapterContentList = chapterContentManager.GetChapterContent(_chapterContent.StandardId,
                _chapterContent.MediumId, _chapterContent.ChapterId, _chapterContent.SectionId, _chapterContent.SubjectId, false);
            return PartialView("_ViewChapterPrint", _chapterContentList.FirstOrDefault());
        }

        [HttpPost]
        public ActionResult DeleteChapterContent(long _chapterContentId)
        {
            bool isDeleted = chapterContentManager.DeleteChapterContent(_chapterContentId);
            return Json(isDeleted);
        }

        [Route("addchaptercontent")]
        [Route("ChapterContent/AddChapterContent")]
        public ActionResult AddChapterContent()
        {
            ChapterContent _chapterContent = new ChapterContent();
            _chapterContent = GetChapterContentObjectDetails(_chapterContent);
            return View(_chapterContent);
        }

        [NonAction]
        public ChapterContent GetChapterContentObjectDetails(ChapterContent _chapterContent)
        {
            _chapterContent.StandardList = standardManager.GetStandardList(null, true).Select(x => new SelectListItem { Text = String.Format("{0} ({1})", x.StandardName, x.Description), Value = x.StandardId.ToString() });
            return _chapterContent;
        }

        [HttpGet]
        public JsonResult GetMediumsByStandardId(long standardId)
        {
            var _mediumList = configurationManager.GetConfiguredStandardMediamConfiguration(standardId)
                .Select(x => new SelectListItem { Text = x.MediumName, Value = x.MediumId.ToString() });

            return Json(_mediumList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetSubjectsByStandardAndMedium(long standardId, long mediumId)
        {
            var _mediumList = configurationManager.GetConfiguredSubjectList(standardId, mediumId)
                .Select(x => new SelectListItem { Text = x.SubjectName, Value = x.SubjectId.ToString() });

            return Json(_mediumList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetChaptersByStandardAndMedium(long standardId, long mediumId, long subjectId)
        {
            var _chapterList = chapterManager.GetChapterListByStandardId(standardId, mediumId, subjectId)
                .Select(x => new SelectListItem { Text = x.ChapterName, Value = x.ChapterId.ToString() });

            return Json(_chapterList, JsonRequestBehavior.AllowGet);
        }



        [HttpGet]
        public JsonResult GetSectionsByChapterId(long chapterId, long mediumId)
        {
            var _sectionList = sectionManager.GetSectionsByChapterId(chapterId, mediumId)
                .Select(x => new SelectListItem { Text = x.SectionName, Value = x.SectionId.ToString() });

            return Json(_sectionList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult InsertChapterContent(ChapterContent _chapterContent)
        {
            if (ModelState.IsValid)
            {
                long result = chapterContentManager.InsertChapterContent(_chapterContent);

                 return RedirectToAction("ListChapterContent");
            }
            else
            {
                return View("AddChapterContent");
            }
        }

        [HttpPost]
        public ActionResult InsertChapterContentText(ChapterContentViewModel _ChapterContentViewModel)
        {
            if (ModelState.IsValid)
            {
                ChapterContent _chapterContent = new ChapterContent();
                _chapterContent.StandardId = _ChapterContentViewModel.StandardId;
                _chapterContent.MediumId = _ChapterContentViewModel.MediumId;
                _chapterContent.SubjectId = _ChapterContentViewModel.SubjectId;
                _chapterContent.ChapterId = _ChapterContentViewModel.ChapterId;
                _chapterContent.SectionId = _ChapterContentViewModel.SectionId;
                _chapterContent.ChapterTextContents = _ChapterContentViewModel.ChapterTextContents;
                _chapterContent.ContentType = ChapterContentType.Text;
                _chapterContent.ContentTypeString = ((int)ChapterContentType.Text).ToString();
                long result = chapterContentManager.InsertChapterContent(_chapterContent);
                return RedirectToAction("ListChapterContent");
            }
            else
            {
                return View("AddChapterContent");
            }
        }


        [HttpPost]
        public ActionResult GetChapterContentListView(long standardId, long mediumId, long subjectId, long chapterId, long sectionId)
        {
            var chapterContentViewModels = chapterContentManager.
                                           GetChapterContent(standardId, mediumId, chapterId, sectionId, subjectId, false);

            return PartialView("_ListChapterContent", chapterContentViewModels);
        }

        [HttpPost]
        public ActionResult ViewChapterContent(ChapterContentViewModel model)
        {
            var _chapterContentList = chapterContentManager.GetChapterContent(model.StandardId,
                model.MediumId, model.ChapterId, model.SectionId, model.SubjectId, false).FirstOrDefault();
            return View(_chapterContentList);
        }

        [HttpPost]
        public JsonResult DisableSection(long chapterId, long sectionId, bool isDisabled)
        {
            var result = chapterContentManager.EnableDisableChapterSection(chapterId, sectionId, isDisabled);
            return Json(result);
        }
    }
}

PrismAdminAPI/Views/ChapterContent/ListChapterContent.cshtml
@model PrismAdminAPI.Models.ChapterContent
@using PrismAdminAPI.Models
@{
    ViewBag.Title = "List Chapter Content";
}
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Chapter Content</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Chapter Content List</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Chapter Content List</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/addchaptercontent" class="btn btn-primary float-right">Add/Edit Chapter Content</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="form-group row">
                                @Html.LabelFor(m => m.StandardId, new { @class = "col-sm-2 col-form-label" })
                                <div class="col-sm-4">
                                    @Html.DropDownListFor(m => m.StandardId, Model.StandardList, "-- Select Standard --", new { @class = "form-control ddlStandards", onchange = "OnStandardChange()" })
                                    @Html.ValidationMessageFor(m => m.StandardId, null, new { @class = "danger errorStandardId" })
                                </div>

                                @Html.LabelFor(m => m.MediumId, new { @class = "col-sm-2 col-form-label" })
                                @Html.HiddenFor(m => m.MediumId)
                                <div class="col-sm-4">
                                    <select class="form-control" id="ddlMediums" onchange="onMediumChange()">
                                        <option selected="selected" value="0">-- Select Mediums --</option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.MediumId, null, new { @class = "danger errorMediumId" })
                                </div>
                            </div>

                            <div class="form-group row">
                                @Html.LabelFor(m => m.SubjectId, new { @class = "col-sm-2 col-form-label" })
                                @Html.HiddenFor(m => m.SubjectId)
                                <div class="col-sm-4">
                                    <select class="form-control" id="ddlSubjects" onchange="onSubjectChange()">
                                        <option selected="selected" value="0">-- Select Subjects --</option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.SubjectId, null, new { @class = "danger errorSubjectId" })
                                </div>
                                @Html.LabelFor(m => m.ChapterId, new { @class = "col-sm-2 col-form-label" })
                        @Html.HiddenFor(m => m.ChapterId)
                                <div class="col-sm-4">
                            <select class="form-control" id="ddlChapters" onchange="onChapterChange()">
                                <option selected="selected" value="0">-- Select Chapters --</option>
                            </select>
                            @Html.ValidationMessageFor(m => m.ChapterId, null, new { @class = "danger errorChapterId" })
                        </div>
                            </div>

                            <div class="form-group row">
                                @Html.LabelFor(m => m.SectionId, new { @class = "col-sm-2 col-form-label" })
                                @Html.HiddenFor(m => m.SectionId)
                                <div class="col-sm-4">
                                    <select class="form-control" id="ddlSections">
                                        <option selected="selected" value="0">-- Select Sections --</option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.SectionId, null, new { @class = "danger errorSectionId" })
                                </div>
                                <div class="col-sm-6">
                                    <button id="btnSearch" class="btn btn-primary">Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <div class="col-12">
                    <div id="divChapterList">
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
</div>
<script src="~/ThemeScript/ChapterContent.js"></script>
<script>

    var _urlMediumList = '@Url.Action("GetMediumsByStandardId", "ChapterContent")';
    var _urlSubjectList = '@Url.Action("GetSubjectsByStandardAndMedium", "ChapterContent")';
    var _urlChapterList = '@Url.Action("GetChaptersByStandardAndMedium", "ChapterContent")';
    var _urlSectionList = '@Url.Action("GetSectionsByChapterId", "ChapterContent")';
    $(document).ready(function () {

        $("#ddlSections").on("change", function () {
            var _sectionId = $(this).val();
            $("#SectionId").val(_sectionId)
        });

        $('#btnSearch').click(function () {
            var standardId = $("#StandardId").val()
            var mediumId = $("#MediumId").val()
            var subjectId = $("#SubjectId").val()
            var chapterId = $("#ChapterId").val()
            var sectionId = $("#SectionId").val()
            $.ajax({
                url: '/ChapterContent/GetChapterContentListView',
                data: { standardId: standardId, mediumId: mediumId, subjectId: subjectId, chapterId: chapterId, sectionId: sectionId },
                datatype: "JSON",
                type: "POST",
                contenttype: 'application/json; charset=utf-8',
                async: true,
                success: function (data) {
                    debugger;
                    $("#divChapterList").html(data);
                },
                error: function (err) {
                    debugger;
                    alert(err.message);
                }
            });
        });
    });
</script>

PrismAdminAPI/Views/ChapterContent/ViewChapterContent.cshtml
@model PrismAdminAPI.Models.ChapterContentViewModel
@using PrismAdminAPI.Models;
@{
    ViewBag.Title = "Edit Chapter Content";
}

<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
<link href="~/Content/editorJSCSS/codemirror.css" rel="stylesheet" />
<link href="~/Content/editorJSCSS/monokai.css" rel="stylesheet" />
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Chapter Content</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Add Chapter Content</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/getchaptercontent" class="btn btn-danger float-right">Chapter Content List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="form-horizontal">
                            <div class="card-body">
                                @using (Html.BeginForm("InsertChapterContentText", "ChapterContent", FormMethod.Post, new { enctype = "multipart/form-data", role = "form", onsubmit = "return OnSubmitClick()" }))
                                {
                                    @Html.ValidationSummary(true);
                                    <div class="card-body">
                                        <div class="form-group row">
                                            @Html.Label("Standard", new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m=>m.StandardId)
                                            <div class="col-sm-4">
                                                @Model.StandardName
                                            </div>

                                            @Html.Label("MediumId", new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m=>m.MediumId)
                                            <div class="col-sm-4">
                                                @Model.MediumName
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            @Html.Label("SubjectId", new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m=>m.SubjectId)
                                            <div class="col-sm-4">
                                                @Model.SubjectName
                                            </div>
                                            @Html.Label("ChapterId", new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m=>m.ChapterId)
                                            <div class="col-sm-4">
                                                @Model.ChapterName
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.Label("SectionId", new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m => m.SectionId)
                                            <div class="col-sm-10">
                                                @Model.SectionName
                                            </div>
                                        </div>
                                        <div class="form-group row ChapterTextContents">
                                            @Html.Label("ChapterContent", new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.TextAreaFor(m=>m.ChapterTextContents, new { rows = "20", style = "resize:none;width:800px;", @class = "form-control input-lg textarea-editor" })
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>
@section scripts{
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
    <link href="~/Content/editorJSCSS/codemirror.css" rel="stylesheet" />
    <link href="~/Content/editorJSCSS/monokai.css" rel="stylesheet" />
    <script src="~/Content/editorJSCSS/summernote.js"></script>
    <script src="~/Content/editorJSCSS/codemirror.js"></script>
    <script src="~/Content/editorJSCSS/xml.js"></script>
    <script src="~/Content/editorJSCSS/formatting.js"></script>
    <script>
        $(document).ready(function () {
            $('.textarea-editor').summernote({
                height: 800,
                width: 850,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture']],
                    ['view', ['fullscreen', 'codeview']]
                ]
            });

        });
    </script>
}

PrismAdminAPI/Views/ChapterContent/_ViewChapterPrint.cshtml
@model PrismAdminAPI.Models.ChapterContentViewModel
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=3, user-scalable=1">
<style>
    .chapter-close-btn {
        margin-top: -16px;
        float: right;
    }

    .modal-header {
        padding: 5px 5px !important;
    }

        .modal-header .close {
            padding: 5px 10px;
            margin: 0px 5px -15px auto;
            background: #337ab7;
        }
</style>
<div class="modal-dialog m-0" style="max-width:inherit;width:100% !important;">
    <div class="modal-content">
        <div class="modal-header section1" style="height: 7vh !important;display:block !important;">
            <span class="modal-title" style="color:black; text-align:left;" id="chapterPagesLabel">View/Print Chapter Content</span>
            <button type="button" class="btn btn-primary close" aria-label="Close" onclick="CloseSectionModel()">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body contentBody" style="padding-left:7px;padding-right:7px;overflow-y: scroll!important;height: 85vh;">
            <div class="row" style="float:right;margin-right:8px;">
                <button class="btn btn-default" style="background-color:mediumslateblue;" onclick="PrintContent()">Print</button>
            </div>
            <div id="DivIdToPrint">

                @if (Model != null)
                {
                    @Html.Raw(Model.ChapterTextContents)
                }
                else
                {
                    <h3>Web site still in progress we will update this shortly!</h3>
                }
            </div>
        </div>
        <div class="modal-footer section1" style="height: 8vh !important;justify-content:flex-start;">
            &nbsp;
        </div>
    </div>
</div>
<script>
    function PrintContent() {
        var divToPrint = document.getElementById('DivIdToPrint');
        var newWin = window.open('', 'Print-Window');
        newWin.document.open();
        newWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</body></html>');
        newWin.document.close();
        setTimeout(function () { newWin.close(); }, 10);
    }  
</script>