PrismAdminAPI/Models/StudentDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Models
{
    public class StudentDetail
    {
        public int LoginId { get; set; }
        public long CouponId { get; set; }
        public string LoginDate { get; set; }
        public string LastLoginDate { get; set; }
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string LastName { get; set; }
        public long MediumId { get; set; }
        public string MediumName { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string DateOfBirth { get; set; }
        public string CouponCode { get; set; }
        public bool IsUsed { get; set; }
        public bool IsActive { get; set; }
        public string SponsorerName { get; set; }

        public List<SelectListItem> MediumList { get; set; } 
    }
}

PrismAdminAPI/Controllers/StudentDetailsController.cs
using PrismAdminAPI.Manager;
using PrismAdminAPI.Manager.StudentDetails;
using PrismAdminAPI.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Web.Mvc;




namespace PrismAdminAPI.Controllers
{
    public class StudentDetailsController : Controller
    {

        private readonly IStudentDetailsManager _studentDetailsManager;
        private readonly IMediumManager _mediumManager;

        public StudentDetailsController(IStudentDetailsManager studentDetailsManager, IMediumManager mediumManager)
        {
            _studentDetailsManager = studentDetailsManager;
            _mediumManager = mediumManager;
        }

        /// <summary>
        /// get all student Details
        /// </summary>
        /// <returns></returns>
        [Route("studentDetails")]
        [Route("StudentDetails/ListStudentDetails")]
        public ActionResult ListStudentDetails()
        {
            //IEnumerable<StudentDetail> _studentDetails = _studentDetailsManager.GetStudentDetails(0,true).Take(1000);
            //IEnumerable<StudentDetail> _studentDetailsFiltered = _studentDetails;
            return View();
        }

        [HttpPost]
        public JsonResult FilterStudentDetails(bool used, long fromCouponId, long toCouponId)
        {
            return Json(GetStudentData(used,fromCouponId,toCouponId).Data, JsonRequestBehavior.AllowGet);
        }


        private JsonResult GetStudentData(bool usedCoupons,long fromCouponId, long toCouponId)
        {
            IEnumerable<StudentDetail> filteredData;
            long totalRecords = 0;
            
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Convert.ToInt32(Request["start"]);
                var length = Convert.ToInt32(Request["length"]);
                var searchvalue = Request["search[value]"];
                var sortcolumn = Request["columns[" + Request["order[0]column"] + "][name]"];
                string sortDirection = Request["order[0][dir]"];
                
              
                if (string.IsNullOrEmpty(searchvalue) && fromCouponId == 0)
                {
                    filteredData = _studentDetailsManager.GetStudentDetails(0, usedCoupons, out long totalrecords, start, length);

                    //{
                    //    filteredData = filteredData.Where(x => !string.IsNullOrEmpty(x.FirstName) && x.FirstName.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.LastName) && x.LastName.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.MediumName) && x.MediumName.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.SponsorerName) && x.SponsorerName.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.CouponCode) && x.CouponCode.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.Password) && x.Password.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.FatherName) && x.FatherName.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.DateOfBirth) && x.DateOfBirth.ToLower().Contains(searchvalue.ToLower())
                    //                            || !string.IsNullOrEmpty(x.PhoneNumber) && x.PhoneNumber.ToLower().Contains(searchvalue.ToLower())).ToList<StudentDetail>();
                    //}
                    totalRecords = totalrecords;
                }
                else 
                {
                    filteredData = _studentDetailsManager.FilterStudentDetails(searchvalue, usedCoupons,fromCouponId,toCouponId);
                    totalRecords = (long)filteredData?.Count();

                }

                if (sortDirection == "asc")
                {
                    if (sortcolumn == "CouponCode")
                        filteredData = filteredData.OrderBy(x => x.CouponCode).ToList<StudentDetail>();
                    else if (sortcolumn == "FirstName")
                        filteredData = filteredData.OrderBy(x => x.FirstName).ToList<StudentDetail>();
                    else if (sortcolumn == "PhoneNumber")
                        filteredData = filteredData.OrderBy(x => x.PhoneNumber).ToList<StudentDetail>();
                    else if (sortcolumn == "LastName")
                        filteredData = filteredData.OrderBy(x => x.LastName).ToList<StudentDetail>();
                    else if (sortcolumn == "SponsorerName")
                        filteredData = filteredData.OrderBy(x => x.SponsorerName).ToList<StudentDetail>();
                }

                if (sortDirection == "desc")
                {
                    if (sortcolumn == "CouponCode")
                        filteredData = filteredData.OrderByDescending(x => x.CouponCode).ToList<StudentDetail>();
                    else if (sortcolumn == "FirstName")
                        filteredData = filteredData.OrderByDescending(x => x.FirstName).ToList<StudentDetail>();
                    else if (sortcolumn == "PhoneNumber")
                        filteredData = filteredData.OrderByDescending(x => x.PhoneNumber).ToList<StudentDetail>();
                    else if (sortcolumn == "LastName")
                        filteredData = filteredData.OrderByDescending(x => x.LastName).ToList<StudentDetail>();
                    else if (sortcolumn == "SponsorerName")
                        filteredData = filteredData.OrderByDescending(x => x.SponsorerName).ToList<StudentDetail>();
                }
                return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = filteredData });

        }

        [HttpGet]
        public JsonResult GetUnusedCoupons(bool used)
        {
            return Json(GetStudentData(used,0,0).Data, JsonRequestBehavior.AllowGet); 
        }

        //[HttpGet]
        //public JsonResult GetFromToCouponData(long fromCoupon, long toCoupon, bool usedCoupons)
        //{
        //    return Json(GetStudentData(usedCoupons, 0, 0).Data, JsonRequestBehavior.AllowGet);
        //}

        /// <summary>
        /// Update Password
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("editPassword/{loginId}")]
        [Route("StudentDetails/EditPassword/{loginId}")]
        public ActionResult EditPassword(StudentDetail detail)
        {
            if (detail.LoginId == 0)
            {
                return View(detail);
            }
            else
            {
                var studentDetail = _studentDetailsManager.GetStudentDetails(detail.LoginId, true, out long totalrecords, 0, 0).FirstOrDefault();
                studentDetail.MediumList = new List<SelectListItem> { };
                var mediumList = _mediumManager.GetMediumList(0, true);
                foreach (var medium in mediumList)
                {
                    studentDetail.MediumList.Add(new SelectListItem { Text = medium.MediumName, Value = medium.MediumId.ToString(), Selected = medium.MediumId == studentDetail.MediumId });
                }

                return View(studentDetail);
            }
        }

        [HttpPost]
        public ActionResult UpdatePassword(StudentDetail detail)
        {
            var studentDetail = _studentDetailsManager.UpdatePassword(detail.LoginId, detail.Password, detail.PhoneNumber, detail.FirstName, detail.LastName, int.Parse(detail.MediumId.ToString()));
            return RedirectToAction("ListStudentDetails");
        }


    }
}

PrismAdminAPI/Views/StudentDetails/EditPassword.cshtml
@model PrismAdminAPI.Models.StudentDetail
@{
    ViewBag.Title = "EditPassword";
}

<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Edit Password</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Edit Password</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Edit Password</h3>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="form-horizontal">
                            <div class="card-body">
                                @using (Html.BeginForm("UpdatePassword", "StudentDetails", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
                                {
                                    @Html.HiddenFor(m => m.LoginId);
                                    @Html.HiddenFor(m => m.IsActive);
                                <div class="card-body">
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.FirstName, new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-5">
                                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.LastName, new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-5">
                                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.MediumName, new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-5">
                                           
                                                @Html.DropDownListFor(m => m.MediumId, Model.MediumList, "-- Select Medium --", new { @class = "form-control ddlSponsorer", id = "mediumId", name = "mediumId" })
                                                @*@Html.ValidationMessageFor(m => m.Medi, null, new { @class = "danger" })*@
                                          
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-5">
                                            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.Password, new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-5">
                                            @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
                                        </div>
                                    </div>

                                </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>

<script>

</script>

PrismAdminAPI/Views/StudentDetails/ListStudentDetails.cshtml
@*@model IEnumerable<PrismAdminAPI.Models.StudentDetail>*@
@{
    ViewBag.Title = "Student Details";
}
<link rel="stylesheet" href="~/ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Student Details</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Student Details</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-3">
                                    <label class="radio-inline">
                                        <input type="radio" id="usedRadio" value="used" name="couponRadio" checked>Used
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" id="unUsedRadio" value="unused" name="couponRadio">Un Used
                                    </label>
                                </div>
                            </div>
                            <div class="row md-2">
                                <div class="col-sm-2">
                                    <input type="number" id="fromNumber" class="form-control" placeholder="From Coupon Id" name="fromNumber">
                                </div>
                                <div class="col-sm-2">
                                    <input type="number" id="toNumber" class="form-control" placeholder="To Coupon Id" name="toNumber">
                                </div>
                                <div class="col-sm-3">
                                    <input type="date" id="lastLoginDate" class="form-control" placeholder="last login date" name="lastLoginDate">
                                </div>
                                <div class="col-sm-2">
                                    <button id="clearDateFilter" class="btn btn-primary form-control">Clear Date</button>
                                </div>
                                <div class="col-sm-3">
                                    <button id="filterData" class="btn btn-primary form-control">Filter</button>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="tblStudentDetails" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Coupon Id</th>
                                        <th>Coupon Code</th>
                                        <th>First Name</th>
                                        <th>Father Name</th>
                                        <th>Last Name</th>
                                        <th>Medium Name</th>
                                        <th>Phone Number</th>
                                        <th>Password</th>
                                        <th>Date Of Birth</th>
                                        <th>Login Date</th>
                                        <th>Last Login Date</th>
                                        <th>Sponsorer Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                @*<tbody>
                                        @foreach (var studentDetail in Model)
                                        {
                                            <tr>
                                                <td>@studentDetail.CouponId</td>
                                                <td>@studentDetail.CouponCode</td>
                                                <td>@studentDetail.FirstName</td>
                                                <td>@studentDetail.FatherName</td>
                                                <td>@studentDetail.LastName</td>
                                                <td>@studentDetail.MediumName</td>
                                                <td>@studentDetail.PhoneNumber</td>
                                                <td>@studentDetail.Password</td>
                                                <td>@studentDetail.DateOfBirth</td>
                                                <td>@(studentDetail.LoginDate)</td>
                                                <td>@(studentDetail.LastLoginDate)</td>
                                                <td>@studentDetail.SponsorerName</td>
                                                <td>
                                                    <button class="btn btn-primary" onclick="javascript: location.href= 'editPassword/@studentDetail.LoginId'">Edit</button>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>*@
                                @*<tfoot>
                                        <tr>
                                            <th>Coupon Id</th>
                                            <th>Coupon Code</th>
                                            <th>First Name</th>
                                            <th>Father Name</th>
                                            <th>Last Name</th>
                                            <th>Medium Name</th>
                                            <th>Phone Number</th>
                                            <th>Password</th>
                                            <th>Date Of Birth</th>
                                            <th>Login Date</th>
                                            <th>Last Login Date</th>
                                            <th>Sponsorer Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>*@
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

    <div id='editPasswordModal' class='modal fade' role="dialog">

    </div>
    <script src="../../ThemeContent/plugins/datatables/jquery.dataTables.js"></script>
    <script src="../../ThemeContent/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/ThemeScript/StudentDetail.js"></script>
    <script src="~/ThemeContent/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/ThemeContent/plugins/jszip/jszip.min.js"></script>
        <script src="~/ThemeContent/plugins/pdfmake/pdfmake.min.js"></script>
        <script src="~/ThemeContent/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/ThemeContent/plugins/datatables-buttons/js/buttons.html5.min.js"></script>


    <script>
        var _urlEditPassword = '@Url.Action("EditPassword", "StudentDetails")'
        var _urlGetUnUsedCoupons = '@Url.Action("GetUnusedCoupons", "StudentDetails")'
        $(function () {
            LoadData(true,0,0);
        });

        function LoadData(used,fromCoupon,toCoupon) {
            var datatable = $('#tblStudentDetails').DataTable();
            if ($.fn.dataTable.isDataTable('#tblStudentDetails')) {
                datatable.clear().destroy();
            }

                $("#tblStudentDetails").DataTable({
                    "serverSide": true,
                    "processing": true,
                    "responsive": true,
                    "search": true,
                    "scrollY":"450px",
                    "paging": true,
                    "lengthchange": false,
                    "scroller": true,
                    "deferRender":true,
                    //"pageLength": 1500,
                    "order": [0, "asc"],
                    "language": {
                        "processing": "Loading records... please wait!!"
                    },
                    dom: 'Bfrtip',
                    buttons: ['excelHtml5'],
                    "ajax": {
                        "url": "/StudentDetails/FilterStudentDetails",
                        "type": "POST",
                        "datatype": "json",
                        "data": {
                            "used": used,
                            "fromCouponId": fromCoupon,
                            "toCouponId": toCoupon,
                        }
                    },
                    "columns": [
                        { "data": "CouponId", "name": "Coupon Id", "autoWidth": true },
                        { "data": "CouponCode", "name": "Coupon Code", "autoWidth": true },
                        { "data": "FirstName", "name": "First Name", "autoWidth": true },
                        { "data": "FatherName", "name": "Father Name", "autoWidth": true },
                        { "data": "LastName", "name": "Last Name", "autoWidth": true },
                        { "data": "MediumName", "name": "Medium Name", "autoWidth": true },
                        { "data": "PhoneNumber", "name": "Phone Number", "autoWidth": true },
                        { "data": "Password", "name": "Password", "autoWidth": true },
                        { "data": "DateOfBirth", "name": "Date Of Birth", "autoWidth": true },
                        { "data": "LoginDate", "name": "Login Date", "autoWidth": true },
                        { "data": "LastLoginDate", "name": "Last Login Date", "autoWidth": true },
                        { "data": "SponsorerName", "name": "Sponsorer Name", "autoWidth": true },
                        {
                            "data": "LoginId",
                            "render": function (data) {
                                return '<button class="btn btn-primary" onclick="'+ "window.open('http://idealstudyadmin.in/StudentDetails/editPassword/" + data + "','_blank')"+'">Edit</button>'
                            }
                        },
                    ],

                });

                var table = $("#tblStudentDetails").DataTable();
                $('#tblStudentDetails_filter input').unbind();
                $('#tblStudentDetails_filter input').bind('keyup', function (e) {
                    if (e.keyCode == 13) {
                        table.search(this.value).draw();
                    }
                });
            
        }
    
    </script>