PrismAdminAPI/Models/SubjectContent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Models
{
    public class SubjectContent
    {
        public long SubjectContentId { get; set; }
        public long StandardId { get; set; }
        public long SubjectId { get; set; }
        public long MediumId { get; set; }
        public long SectionId { get; set; }
        [AllowHtml]
        [DisplayName("Content")]
        public string SubjectTextContents { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }

        public IEnumerable<SelectListItem> StandardList { get; set; }
    }

    public class SubjectContentViewModel
    {
        public long SubjectContentId { get; set; }
        public long SectionId { get; set; }
        public string SectionName { get; set; }

        public long StandardId { get; set; }
        public string StandardName { get; set; }

        public long SubjectId { get; set; }
        public string SubjectName { get; set; }

        public long MediumId { get; set; }
        public string MediumName { get; set; }

        public string SubjectTextContents { get; set; }
        
    }

}

PrismAdminAPI/Controllers/SubjectContentController.cs
using PrismAdminAPI.Manager;
using PrismAdminAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Controllers
{
    public class SubjectContentController : Controller
    {
        private readonly IStandardManager standardManager;
        private readonly IConfigurationManager configurationManager;
        private readonly ISectionManager sectionManager;
        private readonly ISubjectContentManager subjectContentManager;
        public SubjectContentController(
            IStandardManager _standardManager,
            IConfigurationManager _configurationManager,
            ISectionManager _sectionManager,
            ISubjectContentManager _subjectContentManager)
        {
            standardManager = _standardManager;
            configurationManager = _configurationManager;
            sectionManager = _sectionManager;
            subjectContentManager = _subjectContentManager;
        }

        // GET: StandardContent
        [Route("getsubjectcontent")]
        [Route("SubjectContent/ListSubjectContent")]
        public ActionResult ListSubjectContent()
        {
            SubjectContent _subjectContent = new SubjectContent();
            _subjectContent = GetSubjectContentObjectDetails(_subjectContent);
            return View(_subjectContent);
        }

        [HttpPost]
        public ActionResult GetSubjectContent(SubjectContent _subjectContent)
        {
            var _subjectContentList = subjectContentManager.GetSubjectContent(_subjectContent.StandardId,
                _subjectContent.MediumId, _subjectContent.SubjectId, _subjectContent.SectionId);
            return PartialView("_ListSubjectContent", _subjectContentList);
        }

        [Route("addsubjectcontent")]
        [Route("SubjectContent/AddSubjectContent")]
        public ActionResult AddSubjectContent()
        {
            SubjectContent _subjectContent = new SubjectContent();
            _subjectContent = GetSubjectContentObjectDetails(_subjectContent);
            return View(_subjectContent);
        }

        [NonAction]
        public SubjectContent GetSubjectContentObjectDetails(SubjectContent _standardContent)
        {
            _standardContent.StandardList = standardManager.GetStandardList(null, true).Select(x => new SelectListItem { Text = String.Format("{0} ({1})", x.StandardName, x.Description), Value = x.StandardId.ToString() });
            return _standardContent;
        }

        [HttpGet]
        public JsonResult GetMediumsByStandardId(long standardId)
        {
            var _mediumList = configurationManager.GetConfiguredStandardMediamConfiguration(standardId)
                .Select(x => new SelectListItem { Text = x.MediumName, Value = x.MediumId.ToString() });
            return Json(_mediumList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetSubjectsByStandardAndMedium(long standardId, long mediumId)
        {
            var _mediumList = configurationManager.GetConfiguredSubjectList(standardId, mediumId)
                .Select(x => new SelectListItem { Text = x.SubjectName, Value = x.SubjectId.ToString() });

            return Json(_mediumList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetStandardSections()
        {
            var _sectionList=sectionManager.GetSectionList(null,true).Where(x=>x.IsStandardSection==true)
                        .Select(x => new SelectListItem { Text = String.Format("{0}", x.SectionName), Value = x.SectionId.ToString() });
            return Json(_sectionList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult InsertSubjectContent(SubjectContent _subjectContent)
        {
            if (ModelState.IsValid)
            {
                long result = subjectContentManager.InsertSubjectContent(_subjectContent);
                return RedirectToAction("ListSubjectContent");
            }
            else
            {
                return View("AddSubjectContent");
            }
        }

        [HttpGet]
        public ActionResult GetSubjectContentOnSection(SubjectContent _subjectContent)
        {
            var _subjectContentList = subjectContentManager.GetSubjectContent(_subjectContent.StandardId,
                 _subjectContent.MediumId, _subjectContent.SubjectId, _subjectContent.SectionId).FirstOrDefault();
            return Json(_subjectContentList, JsonRequestBehavior.AllowGet);
        }
    }
}

PrismAdminAPI/Views/SubjectContent/AddSubjectContent.cshtml
@model PrismAdminAPI.Models.SubjectContent
@using PrismAdminAPI.Models
@{
    ViewBag.Title = "Add Subject Content";
}
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
<link href="~/Content/editorJSCSS/codemirror.css" rel="stylesheet" />
<link href="~/Content/editorJSCSS/monokai.css" rel="stylesheet" />
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Subject Content</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Subject Content</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Add Subject Content</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/getstandardcontent" class="btn btn-danger float-right">Subject Content List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="form-horizontal">
                            <div class="card-body">
                                @using (Html.BeginForm("InsertSubjectContent", "SubjectContent", FormMethod.Post, new { enctype = "multipart/form-data", role = "form", onsubmit = "return OnSubmitClick()" }))
                                {
                                    @Html.ValidationSummary(true);
                                    <div class="card-body">
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.StandardId, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-4">
                                                @Html.DropDownListFor(m => m.StandardId, Model.StandardList, "-- Select Standard --", new { @class = "form-control ddlStandards", onchange = "OnStandardChange()" })
                                                @Html.ValidationMessageFor(m => m.StandardId, null, new { @class = "danger errorStandardId" })
                                            </div>

                                            @Html.LabelFor(m => m.MediumId, new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m => m.MediumId)
                                            <div class="col-sm-4">
                                                <select class="form-control" id="ddlMediums" onchange="onMediumChange()">
                                                    <option selected="selected" value="0">-- Select Mediums --</option>
                                                </select>
                                                @Html.ValidationMessageFor(m => m.MediumId, null, new { @class = "danger errorMediumId" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.SubjectId, new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m => m.SubjectId)
                                            <div class="col-sm-4">
                                                <select class="form-control" id="ddlSubjects">
                                                    <option selected="selected" value="0">-- Select Subjects --</option>
                                                </select>
                                                @Html.ValidationMessageFor(m => m.MediumId, null, new { @class = "danger errorSubjectId" })
                                            </div>
                                            @Html.LabelFor(m => m.SectionId, new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m => m.SectionId)
                                            <div class="col-sm-4">
                                                <select class="form-control" id="ddlSections">
                                                    <option selected="selected" value="0">-- Select Sections --</option>
                                                </select>
                                                @Html.ValidationMessageFor(m => m.SectionId, null, new { @class = "danger errorSectionId" })
                                            </div>
                                        </div>
                                        <div class="form-group row ChapterTextContents">
                                            @Html.LabelFor(m => m.SubjectTextContents, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.TextAreaFor(m => m.SubjectTextContents, new { @class = "subjectTextContentTextArea textarea-editor" })
                                                @Html.ValidationMessageFor(m => m.SubjectTextContents, null, new { @class = "danger errorSubjectTextContents" })
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>
@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
    <link href="~/Content/editorJSCSS/codemirror.css" rel="stylesheet" />
    <link href="~/Content/editorJSCSS/monokai.css" rel="stylesheet" />
    <script src="~/Content/editorJSCSS/summernote.js"></script>
    <script src="~/Content/editorJSCSS/codemirror.js"></script>
    <script src="~/Content/editorJSCSS/xml.js"></script>
    <script src="~/Content/editorJSCSS/formatting.js"></script>
    <script src="~/ThemeScript/SubjectContent.js"></script>


    <script>
    var _urlMediumList = '@Url.Action("GetMediumsByStandardId", "SubjectContent")';
    var _urlSubjectList = '@Url.Action("GetSubjectsByStandardAndMedium", "SubjectContent")';
    var _urlSectionList = '@Url.Action("GetStandardSections", "SubjectContent")';
    $(document).ready(function () {
       
        $('.textarea-editor').summernote({
            height: 800,
            width: 850,
            toolbar: [
                // [groupName, [list of button]]
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['table', ['table']],
                ['insert', ['link', 'picture']],
                ['view', ['fullscreen', 'codeview']]
            ]
        });
        GetSectionList();

        $("#ddlSubjects").on("change", function () {
            $("#SubjectId").val($(this).val());
        });

        $("#ddlSections").on("change", function () {
            $("#SectionId").val($(this).val());
            BindSubjectContent();
        });
    });


    function BindSubjectContent() {
        var _subjectContent = {};

        _subjectContent.StandardId = $(".ddlStandards").val();
        _subjectContent.MediumId = $("#ddlMediums").val();
        _subjectContent.SubjectId = $("#ddlSubjects").val();
        _subjectContent.SectionId = $("#ddlSections").val();

        $.ajax({
            type: "GET",
            url: "/SubjectContent/GetSubjectContentOnSection",
            data: _subjectContent,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (response) {
                debugger
                if (response != null && response != undefined && response.SubjectTextContents != null) {
                    $('.textarea-editor').summernote({
                        height: 800,
                        width: 850,
                        toolbar: [
                            // [groupName, [list of button]]
                            ['style', ['bold', 'italic', 'underline', 'clear']],
                            ['font', ['strikethrough', 'superscript', 'subscript']],
                            ['fontsize', ['fontsize']],
                            ['color', ['color']],
                            ['para', ['ul', 'ol', 'paragraph']],
                            ['height', ['height']],
                            ['table', ['table']],
                            ['insert', ['link', 'picture']],
                            ['view', ['fullscreen', 'codeview']]
                        ]
                    });
                    $('.textarea-editor').summernote('code', response.SubjectTextContents);
                }
            },
            error: function (response) {

            }
        });
    }

    </script>
}

PrismAdminAPI/Views/SubjectContent/ListSubjectContent.cshtml
@model PrismAdminAPI.Models.SubjectContent
@using PrismAdminAPI.Models
@{
    ViewBag.Title = "Add Subject Content";
}
<link href="~/ThemeContent/summernote/summernote.min.css" rel="stylesheet" />
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Subject Content</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Subject Content</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Add Subject Content</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/addsubjectcontent" class="btn btn-danger float-right">Add Subject Content</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="form-horizontal">
                            <div class="card-body">
                                <div class="card-body">
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.StandardId, new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-4">
                                            @Html.DropDownListFor(m => m.StandardId, Model.StandardList, "-- Select Standard --", new { @class = "form-control ddlStandards", onchange = "OnStandardChange()" })
                                            @Html.ValidationMessageFor(m => m.StandardId, null, new { @class = "danger errorStandardId" })
                                        </div>

                                        @Html.LabelFor(m => m.MediumId, new { @class = "col-sm-2 col-form-label" })
                                        @Html.HiddenFor(m => m.MediumId)
                                        <div class="col-sm-4">
                                            <select class="form-control" id="ddlMediums" onchange="onMediumChange()">
                                                <option selected="selected" value="0">-- Select Mediums --</option>
                                            </select>
                                            @Html.ValidationMessageFor(m => m.MediumId, null, new { @class = "danger errorMediumId" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.SubjectId, new { @class = "col-sm-2 col-form-label" })
                                        @Html.HiddenFor(m => m.SubjectId)
                                        <div class="col-sm-4">
                                            <select class="form-control" id="ddlSubjects">
                                                <option selected="selected" value="0">-- Select Subjects --</option>
                                            </select>
                                            @Html.ValidationMessageFor(m => m.SubjectId, null, new { @class = "danger errorSubjectId" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(m => m.SectionId, new { @class = "col-sm-2 col-form-label" })
                                        @Html.HiddenFor(m => m.SectionId)
                                        <div class="col-sm-4">
                                            <select class="form-control" id="ddlSections">
                                                <option selected="selected" value="0">-- Select Sections --</option>
                                            </select>
                                            @Html.ValidationMessageFor(m => m.SectionId, null, new { @class = "danger errorSectionId" })
                                        </div>
                                        <div class="col-sm-6">
                                            <button id="btnSearch" class="btn btn-primary">Search</button>
                                        </div>
                                    </div>
                                    <div id="divSubjectContent">

                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>
@section scripts{
    <script src="~/ThemeScript/SubjectContent.js"></script>
    <script>
    var _urlMediumList = '@Url.Action("GetMediumsByStandardId", "SubjectContent")';
    var _urlSectionList = '@Url.Action("GetStandardSections", "SubjectContent")';
    var _urlSubjectList = '@Url.Action("GetSubjectsByStandardAndMedium", "SubjectContent")';
    $(document).ready(function () {
        GetSectionList();
        BindSubjectContent();
        $("#btnSearch").click(function () {
            BindSubjectContent();
        });
        $("#ddlSubjects").on("change", function () {
            $("#SubjectId").val($(this).val());
        });

        $("#ddlSections").on("change", function () {
            $("#SectionId").val($(this).val());
        });
    });


    function BindSubjectContent() {
            var _subjectContent = {
                StandardId: $(".ddlStandards").val(),
                MediumId: $("#ddlMediums").val(),
                SubjectId: $("#ddlSubjects").val(),
                SectionId: $("#ddlSections").val()
            }
            $.ajax({
                type: "POST",
                url: "/SubjectContent/GetSubjectContent",
                data: JSON.stringify(_subjectContent),
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (response) {
                    $('#divSubjectContent').html(response);
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        }

    </script>
}

PrismAdminAPI/Views/SubjectContent/_ListSubjectContent.cshtml
@model IEnumerable<PrismAdminAPI.Models.SubjectContentViewModel>
@using PrismAdminAPI.Models;
@{
    ViewBag.Title = "List Subject Content";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<table id="tblStandardContent" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Standard </th>
            <th>Subject </th>
            <th>Medium</th>
            <th>Section</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.StandardName</td>
            <td>@item.SubjectName</td>
            <td>@item.MediumName</td>
            <td>@item.SectionName</td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Standard </th>
            <th>Subject </th>
            <th>Medium</th>
            <th>Section</th>
        </tr>
    </tfoot>
</table>

<script src="../../ThemeContent/plugins/datatables/jquery.dataTables.js"></script>
<script src="../../ThemeContent/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="~/ThemeScript/SubjectContent.js"></script>
<script>
    $(function () {
        $('#tblStandardContent').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });
</script>